specVersion: 0.2.0
name: pangolin-dictionary
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-dictionary.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x46720335bb0a5c81a29777a9ad81afcda36b70f34103ebea42fb55332a1b79b4'
  endpoint: wss://pangolin-rpc.darwinia.network
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
