specVersion: 0.2.0
name: pangoro-dictionary
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-dictionary.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x1fe062d52429523226af0570f59dcc19fa0b0b841377d9f530b618deedf2eef5'
  endpoint: wss://pangoro-rpc.darwinia.network/
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
